hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /uaa/**
      url: http://auth-service:8762
      stripPrefix: true
      sensitiveHeaders:
    system-service:
      path: /system/**
      url: http://auth-service:8763
      stripPrefix: true
      sensitiveHeaders:


server:
  port: 4000
