hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    auth-service:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: auth
    system-service:
      path: /system/**
      sensitiveHeaders:
      serviceId: system



server:
  port: 4000
